# verwende das Image microsoft/aspnetcore-build und gib den Namen 'build'
FROM microsoft/aspnetcore-build ...

# setz das working directory auf '/app'

# kopiere die #.csproj Datei in das working directory

# führe den Befehl 'dotnet resore' aus

# kopiere die restlichen Dateien aus dem aktuellen Verzeichnis in das working directory

# führe den Befehl 'dotnet publish -c Release -o out' aus

# verwende jetzt das Image microsoft/aspnetcore

# setze auch hier das working directory auf '/app'

# kopiere den output des 'build' Images vom Verzeichnis '/app/out' in das working directory

# erstelle ein Verzeichnis 'db' im working directory

ENTRYPOINT [ "dotnet", "TodoApi.dll" ]
